version: '3.8'

services:
  server:
    build:
      context: server
    environment:
      SERVER_PORT: 8000

  haproxy:
    image: haproxy:2.5.3
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - '80:80'
