version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile

  nginx:
    image: nginx:1.19.4
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - '80:80'
