version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    healthcheck:
      test: [ "CMD", "grpc-health-probe", "-addr", "server:50051" ]
      interval: 5s
      timeout: 5s
      retries: 3

  nginx:
    image: nginx:1.19.4
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - '80:80'
