version: '3.8'

services:
  vault:
    image: vault:1.5.5
    container_name: vault
    cap_add:
      - IPC_LOCK # prevents memory from being swapped to disk
    ports:
      - "8200:8200"
    environment:
      VAULT_ADDR: "http://127.0.0.1:8200" # use HTTP in dev mode
