version: '3.8'

services:
  server:
    build:
      context: server
    environment:
      SERVER_PORT: 8000

  nginx:
    image: nginx:1.21.6
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - '80:80'
